title: Tommy's Portfolio
author: Tommy Garner
email: tgarn0113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here's my portfolio sites that host my code and blog posts about anything sports, music, media, and miscellaneous!

# social links
github_username: tommygarner

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
markdown: kramdown
